CONTRIBUTING.md, README.md
Will need to update link to style guide when available, see #11.
Closes #10
=> docs-11-git-workflow

README.md, app/adapters/application.js, app/serializers/application.js, app/transforms/json.js, bower.json, package.json, tests/unit/adapters/application-test.js, tests/unit/serializers/application-test.js, tests/unit/transforms/json-test.js
Require the ember-local-storage addon.
Make localstorage the application default.
Added a json transform.
Closes #21
=> Adds feature-21-localstorage

LICENSE
=> Change License to GPL v3

lib/ember-leaflet-table/addon/components/leaflet-draw.js, lib/ember-leaflet-table/addon/components/leaflet-table.js, lib/ember-leaflet-table/addon/components/lgeojson-layer.js
=> Fix spatial uuid generation

app/pods/components/object/md-keyword-citation/component.js, app/pods/components/object/md-lineage/template.hbs, app/services/patch.js, app/templates/application.hbs
=> Fix 172 lineage source description

.travis.yml, config/ember-try.js, package.json, tests/helpers/destroy-app.js, tests/helpers/module-for-acceptance.js, tests/helpers/start-app.js, tests/test-helper.js
Update ember test suite to be compatible with ember release.
Modify ember-try config to only test builds until 1.0 release.
=> Update ember-try, travis config

app/models/base.js, app/models/contact.js, app/models/record.js, app/models/setting.js, app/pods/components/md-translate/component.js, app/pods/export/template.hbs, app/pods/settings/route.js, app/pods/settings/template.hbs, lib/ember-leaflet-table/addon/components/leaflet-table.js
=> Tweaks and bug fixes

CHANGELOG.md, package.json
=> Released v0.2.1

app/index.html, app/pods/components/md-title/component.js, app/pods/components/md-title/template.hbs, app/pods/components/object/md-locale/component.js, app/pods/record/new/id/template.hbs, app/pods/record/show/edit/metadata/index/route.js, app/services/mdjson.js, app/templates/application.hbs, app/templates/head.hbs, package-lock.json, package.json, tests/integration/pods/components/md-title/component-test.js
=> Breadcrumb Titles and memberOfOrganization fix

app/services/mdjson.js, app/services/patch.js
=> Fix Contacts in mdJSON

CHANGELOG.md, package.json
=> Released v0.3.1

app/pods/dictionary/show/edit/template.hbs, app/pods/export/template.hbs, app/pods/import/template.hbs, app/pods/record/show/edit/associated/resource/index/template.hbs, app/pods/record/show/edit/distribution/distributor/index/template.hbs, app/pods/record/show/edit/documents/citation/index/template.hbs, app/pods/record/show/edit/funding/allocation/template.hbs, app/pods/record/show/edit/keywords/template.hbs, app/pods/record/show/edit/lineage/lineageobject/citation/identifier/template.hbs, app/pods/record/show/edit/lineage/lineageobject/citation/index/template.hbs, app/pods/record/show/edit/lineage/lineageobject/index/template.hbs, app/pods/record/show/edit/lineage/lineageobject/source/index/template.hbs, app/pods/record/show/edit/lineage/lineageobject/step/citation/template.hbs, app/pods/record/show/edit/lineage/lineageobject/step/index/template.hbs, app/pods/record/show/edit/main/citation/identifier/template.hbs, app/pods/record/show/edit/main/citation/index/template.hbs, app/pods/record/show/edit/main/index/template.hbs, app/pods/record/show/edit/metadata/alternate/identifier/template.hbs, app/pods/record/show/edit/metadata/alternate/index/template.hbs, app/pods/record/show/edit/metadata/identifier/template.hbs, app/pods/record/show/edit/metadata/index/template.hbs, app/pods/record/show/edit/metadata/parent/identifier/template.hbs, app/pods/record/show/edit/metadata/parent/index/template.hbs, app/pods/record/show/edit/taxonomy/collection/index/template.hbs, app/pods/record/show/edit/taxonomy/collection/system/index/template.hbs, app/pods/record/show/edit/taxonomy/index/template.hbs, app/pods/record/show/edit/template.hbs, package-lock.json, package.json, yarn.lock
=> Feature 101 taxonomy

CHANGELOG.md, yarn.lock
=> Maintenance 255 ember3

yarn.lock
=> Fix production build

app/pods/components/object/md-allocation/template.hbs, app/pods/import/template.hbs, app/services/patch.js, tests/integration/pods/components/object/md-allocation/component-test.js
=> More Bug fixes for v0.8.0

app/models/base.js, app/models/contact.js, app/models/dictionary.js, app/models/record.js, app/models/schema.js, app/pods/components/control/md-edit-table/component.js, app/pods/components/control/md-errors/component.js, app/pods/components/control/md-errors/template.hbs, app/pods/components/control/md-status/template.hbs, app/pods/components/md-models-table/components/row-buttons/template.hbs, app/pods/components/object/md-schema/form/template.hbs, app/pods/contacts/template.hbs, app/pods/dictionary/show/edit/template.hbs, app/pods/dictionary/show/template.hbs, app/pods/records/template.hbs, app/pods/settings/validation/controller.js, app/pods/settings/validation/template.hbs, app/routes/application.js, app/services/schemas.js, app/styles/_form_elements.scss, app/styles/_validation.scss, package.json, tests/integration/pods/components/control/md-errors/component-test.js, tests/integration/pods/components/object/md-schema/component-test.js, tests/integration/pods/components/object/md-schema/form/component-test.js, yarn.lock
=> Feature 299 custom schema

app/styles/_form_elements.scss
```
.md-input-input {
position: relative;
>input[placeholder] {
text-overflow: ellipsis;
padding-right: 30px;
}
}
```
Closes #338
=> - Added css overflow to inputs to help truncate longer text.

app/pods/components/object/md-domainitem/template.hbs, tests/integration/pods/components/object/md-associated/preview/component-test.js, tests/integration/pods/components/object/md-domainitem/component-test.js
=> Changed domain-item from md-input over to md-textarea

.gitignore, app/pods/contact/show/index/template.hbs
```
{{#unless model.json.isOrganization}}
{{control/md-definition title="Position" text=model.json.positionName}}
{{/unless}}
```
Closes: #362
=> Fixed "Postion" in contact.show.index route

.gitignore, app/pods/components/object/md-domain/template.hbs, app/pods/components/object/md-entity/template.hbs, tests/integration/pods/components/object/md-associated/preview/component-test.js, tests/integration/pods/components/object/md-domain/component-test.js, tests/integration/pods/components/object/md-entity/component-test.js
- #### app/pods/components/object/md-entity/template.hbs
---
- #### app/pods/components/object/md-domain/template.hbs
---
- #### app/pods/components/object/md-entity/template.hbs
Resolves #276 
Resolves #278 
Resolves #273
=> Minor spelling and label fixes

CHANGELOG.md, package.json
=> Bump version, update CHANGELOG

.travis.yml, app/models/setting.js, app/pods/components/control/md-modal/component.js, app/pods/components/control/md-modal/template.hbs, app/pods/settings/main/template.hbs, app/pods/settings/route.js, package.json, tests/integration/pods/components/control/md-modal/component-test.js, yarn.lock
=> Mixed 379 257 clear cache

.gitignore, .travis.yml, app/models/setting.js, app/pods/components/control/md-modal/component.js, app/pods/components/control/md-modal/template.hbs, app/pods/settings/main/template.hbs, app/pods/settings/route.js, app/routes/application.js, package.json, tests/integration/pods/components/control/md-modal/component-test.js, yarn.lock
=> Fix 382 avoid race

package.json, yarn.lock
=> Adding resolutions value to package.json until update dependency.

app/adapters/application.js, app/models/base.js, app/pods/components/layout/md-footer/component.js, app/pods/components/layout/md-footer/template.hbs, app/pods/record/new/id/route.js, app/routes/application.js, app/services/local-storage-monitor.js, app/utils/md-object-size.js, tests/integration/pods/components/layout/md-footer/component-test.js, tests/unit/services/local-storage-monitor-test.js, tests/unit/utils/md-object-size-test.js
repaired merge conflicts 
closes #394
=> Dvonanderson enhancement 157/local storage limit

app/models/dictionary.js, app/services/mdjson.js
https://github.com/adiwg/mdTranslator/issues/238
=> actually import / export dictionaryId

config/environment.js
Changed root url to just `"/"` instead of `"/mdEditor"`.
Closes #500
=> fix(environment.js): change root url for staging environment

codemods.log
=> removed codemods log.

package.json
=> update dev version to 0.11.0-dev.1

app/pods/components/md-help/template.hbs
Closes #495 
https://github.com/adiwg/mdEditor/issues/495
=> Hide `Join Email list` button

package.json
version to dev.2
* **Does this PR …
=> Update develop to version dev.2

app/pods/contact/show/edit/template.hbs
closes #420
Update model.json.contactInstruction to model.json.contactInstructions
Seems to work locally. @dvonanderson can you make sure that this is all that's needed.
=> Fix contact instructions

Dockerfile
Closes #591 
Dockerfile node version changed from 14 to 16
=> Update Node Version to 16

app/initializers/local-storage-export.js, app/pods/components/control/md-modal/component.js
closes #596 
- Fixes export selected functionality for editor
https://github.com/adiwg/mdEditor/issues/596
- Functionality works as designed.
* **Other information**:
https://github.com/adiwg/mdEditor/assets/24277002/873e4fd0-07f6-46c1-84cc-4888260fb00a
=> [BUG] #596 Fix export selected function

package.json, yarn.lock
closes #600 
- Upgrade dependencies
https://github.com/adiwg/mdEditor/issues/600
- No specific change
=> [Upgrade] #600 upgrade mdEditor to latest version of `mdSchema`

app/pods/components/object/md-keyword-citation/component.js, app/pods/components/object/md-keyword-citation/template.hbs
Fixed the keyword hanging bug.
Will deploy a test container and then updated this comment.
=> 599 keywords functioning hangs with legacy data

package.json
Update develop branch to v1.0.3 in preparation for release.
Removed `private` key from package.json - does not apply to web applications.
=> Update to v1.0.3

package.json
closes #628 
Update version prior to deploying
=> Bump version to 1.1.0 and deploy update

app/pods/components/md-translate/component.js, package.json
Closes #602 
- Renamed 19115-1 to 19115-3
- Renamed 19115-2 to 19115-2/19139 (deprecated)
- Increment version to 1.2.0
http://23.23.4.125:8001/
=> Renamed Iso 19115 -1 / -2

app/pods/components/md-models-table/component.js, lib/ember-leaflet-table/addon/components/feature-table.js, lib/ember-leaflet-table/addon/components/leaflet-draw.js, lib/ember-leaflet-table/addon/templates/components/leaflet-table.hbs, lib/ember-leaflet-table/package.json, package.json, yarn.lock
- Create an extent on any record and add features
https://github.com/adiwg/mdEditor/assets/24277002/6ce2485e-4728-4191-8e13-55203c41c99b
closes #597 
closes #598 
~~  - [ ] Docs have been added / updated (for bug fixes / features)~~
- Allow users to create features on extent maps
https://github.com/adiwg/mdEditor/issues/597
https://github.com/adiwg/mdEditor/issues/598
- Feature behaves as intended
=> Clean up logic for extent to allow creation and viewing of features

.gitignore, CONTRIBUTING.md, app/pods/components/md-models-table/component.js, app/pods/components/md-translate/component.js, app/services/keycloak.js, config/environment.js, lib/ember-leaflet-table/addon/components/feature-table.js, lib/ember-leaflet-table/addon/components/leaflet-draw.js, lib/ember-leaflet-table/addon/templates/components/leaflet-table.hbs, lib/ember-leaflet-table/package.json, lib/mdeditor-sciencebase/addon/components/sb-publisher.js, lib/mdeditor-sciencebase/addon/templates/components/sb-publisher.hbs, lib/mdeditor-sciencebase/addon/utils/config.js, lib/mdeditor-sciencebase/addon/utils/sb-tree-node.js, package.json, public/404.html, tests/integration/components/sb-publisher-test.js, tests/unit/services/keycloak-test.js, yarn.lock
merge develop v1.2.0-dev.2 and deploy
=> Merge develop into master

app/pods/components/object/md-extent/template.hbs, app/pods/components/object/md-extent/temporal/component.js, app/pods/components/object/md-extent/temporal/template.hbs, app/pods/components/object/md-extent/vertical/component.js, app/pods/components/object/md-extent/vertical/template.hbs, app/pods/record/show/edit/extent/route.js, app/services/mdjson.js
Merging into adiwg branch to review changes.
=> Add temporal and vertical extents

app/pods/components/object/md-source/template.hbs, package.json
Closes #491 
Increment Version to v1.3.0-beta.2
- Double quotes replaced with single quotes (code formatting)
- Removed `simpleIdentifier=true` (line 45)
- Removed `embedded=true` (line 47)
http://23.23.4.125:8001/ [v1.3.0-beta.2]
=> Refactor Lineage Source Citation

app/pods/components/object/md-citation/preview/body/template.hbs, package.json
Closes #205 
v1.4.0-beta.?
- Updated date format for citation preview
- app/pods/components/object/md-citation/preview/body/template.hbs line 23 -> line 28: `{{moment-format date.date "MMMM Do YYYY"}}` -> `{{moment-format date.date 'YYYY-MM-DD'}}`
- Code formatting
=> Dates are displayed in a non standard format

app/pods/components/input/md-datetime/component.js, app/pods/components/input/md-datetime/template.hbs, package.json
Closes #246 
v1.4.0-beta.?
- Cleaned up, removed excess
- Ability to add time, in addition to date
=> Refactor md-datetime template to use single quotes for HTML attributes

app/pods/components/object/md-constraint/component.js, app/pods/components/object/md-constraint/template.hbs, package.json, yarn.lock
Closes #570 
Increment Version to 1.4.0-beta.15
- Code formatting (only in modified files)
- app/pods/components/object/md-constraint/component.js added releasability initialization
- app/pods/components/object/md-constraint/template.hbs removed commented code and added releasability section
Updated 4/10/2024
http://23.23.4.125:8002/
=> Add support for limits of use and licensing

package.json
Update version to v1.3.0-rc.1 prior to deploying develop branch for final testing.
=> bump dev version to 1.3.0-rc.1

.github/ISSUE_TEMPLATE/new-issue.md
Convert issue template to new format
=> Update issue templates

Dockerfile
Upgrade Dockerfile to work with newer build process.
=> Update Dockerfile to use Node.js 20 and enable Corepack

app/pods/components/control/md-errors/component.js
Closes #731 
Closes #724 
Issue: Go To Error Button Does Not Work When Viewing (Not Editing) a Record
- Enhanced regex to find the record id
Issue: Validation error "Minimum Items Required for Contacts" links to wrong path
- Added messages to the /contacts error to clarify why the error is being displayed
=> Resolve issues 724 & 731

app/models/schema.js
closes #728 
~~- [ ] Docs have been added / updated (for bug fixes / features)~~
Bug fix for `ajv-error` console.log error when user clicks on `Add Schema`
#728
Feature works as designed
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no
* **Other information**:
https://github.com/user-attachments/assets/18ff2485-b04f-462f-8dac-d2ada369b9f4
=> Fix `ajv-error` import statement

package.json, yarn.lock
Use mdjson-schemas v2.10.2
Bump dev version to v1.3.0-rc.2
Update yarn.lock
Closes #717
=> Bump dev version to v1.3.0-rc.2

app/mixins/object-template.js
- Verify validation state updates correctly when adding/removing array items
- Check validation propagation through component hierarchy
- Test array template application with various validation scenarios
closes #610 
closes #712 
closes #743 
~~- [ ] Docs have been added / updated (for bug fixes / features)~~
- Added validation state propagation in applyTemplateArray method
- Improved template application lifecycle with validation hooks
- Added support for component-level validation through validateArray callback
- Fixes validation state issues with resource type arrays …
=> Bug:  Fix form data not saving correctly.

CONTRIBUTING.md
=> Update CONTRIBUTING to add guidelines for use of user specified defaults

package.json
Bump version to identify testing deployment.
- #752 
- #610
- #712
- #743
- #734
- #740
- #744 
- #754
=> bump dev version to 1.3.0-RC.3

app/mixins/object-template.js, app/pods/components/object/md-array-table/component.js, app/pods/components/object/md-resource-type-array/component.js
closes #759 
- Modified the md-array-table component to conditionally use different template application strategies based on whether the array is new or existing
- Added tracking of previous array values to determine the appropriate template strategy
- Implemented a separate templated value property to avoid auto-tracking assertion errors
- Updated the arrayValues computed property to use the templated value when available
- Maintained backward compatibility with existing component usage patterns
#759 
works as designed …
=> Temporary work around for the `object-template.js` mixin

package.json
=> bump dev version to 1.3.0-rc.4
